name: learning_about_b4a_flutter
description: Learning about back4app.com com Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  # Backend com back4app.com
  parse_server_sdk_flutter: ^3.1.3
  # Gerencia de estados
  get: ^4.6.5
  # Variáveis de ambiente
  flutter_dotenv: ^5.0.2
  # Imagem
  image_picker: ^0.8.5+3
  # dotted_border: ^2.0.0+2
  # image_cropper: ^3.0.0
  image_picker_for_web: ^2.1.8
  # outros
  validatorless: ^1.2.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
